server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/ydg_clinic
spring.datasource.username=ydg_user
spring.datasource.password=ydg_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
